spring:
  application:
    name: reactive-elasticsearch-client-poc
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: 192.168.1.6:9200
  elasticsearch:
    rest:
      uris: http://192.168.1.6:9200
     
initial-import:
  enabled: false